#=================================================================
# 对象存储配置
#=================================================================
storage:
  minio:
    endpoint: http://182.92.185.232:19000
    accessKey: iqBmEXjX2rcmJzRpQ2jx
    secretKey: 0fRzZl6DGfk73tdSBtR9ebw4sLkkuJv6jZ4ehdeQ

spring:
  servlet:
    multipart:
      max-file-size: 50MB      # 单个文件最大大小（根据需求调整，如 1GB）
      max-request-size: 50MB   # 单次请求总大小

